# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := lib9 libbio libsec ndate node9 libnode9

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

lib9: 
	@echo "==== Building lib9 ($(config)) ===="
	@${MAKE} --no-print-directory -C src/styx/libs/lib9 -f Makefile

libbio: 
	@echo "==== Building libbio ($(config)) ===="
	@${MAKE} --no-print-directory -C src/styx/libs/libbio -f Makefile

libsec: 
	@echo "==== Building libsec ($(config)) ===="
	@${MAKE} --no-print-directory -C src/styx/libs/libsec/port -f Makefile

ndate: 
	@echo "==== Building ndate ($(config)) ===="
	@${MAKE} --no-print-directory -C src/styx/utils -f Makefile

node9: 
	@echo "==== Building node9 ($(config)) ===="
	@${MAKE} --no-print-directory -C src -f node9.make

libnode9: 
	@echo "==== Building libnode9 ($(config)) ===="
	@${MAKE} --no-print-directory -C src -f libnode9.make

clean:
	@${MAKE} --no-print-directory -C src/styx/libs/lib9 -f Makefile clean
	@${MAKE} --no-print-directory -C src/styx/libs/libbio -f Makefile clean
	@${MAKE} --no-print-directory -C src/styx/libs/libsec/port -f Makefile clean
	@${MAKE} --no-print-directory -C src/styx/utils -f Makefile clean
	@${MAKE} --no-print-directory -C src -f node9.make clean
	@${MAKE} --no-print-directory -C src -f libnode9.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   lib9"
	@echo "   libbio"
	@echo "   libsec"
	@echo "   ndate"
	@echo "   node9"
	@echo "   libnode9"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
