# GNU Make solution makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug_linux
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_linux)
  lib9_config = debug_linux
  libbio_config = debug_linux
  libsec_config = debug_linux
  ndate_config = debug_linux
  node9_config = debug_linux
  libnode9_config = debug_linux
endif
ifeq ($(config),debug_macosx)
  lib9_config = debug_macosx
  libbio_config = debug_macosx
  libsec_config = debug_macosx
  ndate_config = debug_macosx
  node9_config = debug_macosx
  libnode9_config = debug_macosx
endif
ifeq ($(config),debug_freebsd)
  lib9_config = debug_freebsd
  libbio_config = debug_freebsd
  libsec_config = debug_freebsd
  ndate_config = debug_freebsd
  node9_config = debug_freebsd
  libnode9_config = debug_freebsd
endif
ifeq ($(config),debug_netbsd)
  lib9_config = debug_netbsd
  libbio_config = debug_netbsd
  libsec_config = debug_netbsd
  ndate_config = debug_netbsd
  node9_config = debug_netbsd
  libnode9_config = debug_netbsd
endif
ifeq ($(config),debug_openbsd)
  lib9_config = debug_openbsd
  libbio_config = debug_openbsd
  libsec_config = debug_openbsd
  ndate_config = debug_openbsd
  node9_config = debug_openbsd
  libnode9_config = debug_openbsd
endif
ifeq ($(config),debug_dragonfly)
  lib9_config = debug_dragonfly
  libbio_config = debug_dragonfly
  libsec_config = debug_dragonfly
  ndate_config = debug_dragonfly
  node9_config = debug_dragonfly
  libnode9_config = debug_dragonfly
endif
ifeq ($(config),debug_solaris)
  lib9_config = debug_solaris
  libbio_config = debug_solaris
  libsec_config = debug_solaris
  ndate_config = debug_solaris
  node9_config = debug_solaris
  libnode9_config = debug_solaris
endif
ifeq ($(config),debug_windows)
  lib9_config = debug_windows
  libbio_config = debug_windows
  libsec_config = debug_windows
  ndate_config = debug_windows
  node9_config = debug_windows
  libnode9_config = debug_windows
endif
ifeq ($(config),debug_android)
  lib9_config = debug_android
  libbio_config = debug_android
  libsec_config = debug_android
  ndate_config = debug_android
  node9_config = debug_android
  libnode9_config = debug_android
endif
ifeq ($(config),devel_linux)
  lib9_config = devel_linux
  libbio_config = devel_linux
  libsec_config = devel_linux
  ndate_config = devel_linux
  node9_config = devel_linux
  libnode9_config = devel_linux
endif
ifeq ($(config),devel_macosx)
  lib9_config = devel_macosx
  libbio_config = devel_macosx
  libsec_config = devel_macosx
  ndate_config = devel_macosx
  node9_config = devel_macosx
  libnode9_config = devel_macosx
endif
ifeq ($(config),devel_freebsd)
  lib9_config = devel_freebsd
  libbio_config = devel_freebsd
  libsec_config = devel_freebsd
  ndate_config = devel_freebsd
  node9_config = devel_freebsd
  libnode9_config = devel_freebsd
endif
ifeq ($(config),devel_netbsd)
  lib9_config = devel_netbsd
  libbio_config = devel_netbsd
  libsec_config = devel_netbsd
  ndate_config = devel_netbsd
  node9_config = devel_netbsd
  libnode9_config = devel_netbsd
endif
ifeq ($(config),devel_openbsd)
  lib9_config = devel_openbsd
  libbio_config = devel_openbsd
  libsec_config = devel_openbsd
  ndate_config = devel_openbsd
  node9_config = devel_openbsd
  libnode9_config = devel_openbsd
endif
ifeq ($(config),devel_dragonfly)
  lib9_config = devel_dragonfly
  libbio_config = devel_dragonfly
  libsec_config = devel_dragonfly
  ndate_config = devel_dragonfly
  node9_config = devel_dragonfly
  libnode9_config = devel_dragonfly
endif
ifeq ($(config),devel_solaris)
  lib9_config = devel_solaris
  libbio_config = devel_solaris
  libsec_config = devel_solaris
  ndate_config = devel_solaris
  node9_config = devel_solaris
  libnode9_config = devel_solaris
endif
ifeq ($(config),devel_windows)
  lib9_config = devel_windows
  libbio_config = devel_windows
  libsec_config = devel_windows
  ndate_config = devel_windows
  node9_config = devel_windows
  libnode9_config = devel_windows
endif
ifeq ($(config),devel_android)
  lib9_config = devel_android
  libbio_config = devel_android
  libsec_config = devel_android
  ndate_config = devel_android
  node9_config = devel_android
  libnode9_config = devel_android
endif
ifeq ($(config),release_linux)
  lib9_config = release_linux
  libbio_config = release_linux
  libsec_config = release_linux
  ndate_config = release_linux
  node9_config = release_linux
  libnode9_config = release_linux
endif
ifeq ($(config),release_macosx)
  lib9_config = release_macosx
  libbio_config = release_macosx
  libsec_config = release_macosx
  ndate_config = release_macosx
  node9_config = release_macosx
  libnode9_config = release_macosx
endif
ifeq ($(config),release_freebsd)
  lib9_config = release_freebsd
  libbio_config = release_freebsd
  libsec_config = release_freebsd
  ndate_config = release_freebsd
  node9_config = release_freebsd
  libnode9_config = release_freebsd
endif
ifeq ($(config),release_netbsd)
  lib9_config = release_netbsd
  libbio_config = release_netbsd
  libsec_config = release_netbsd
  ndate_config = release_netbsd
  node9_config = release_netbsd
  libnode9_config = release_netbsd
endif
ifeq ($(config),release_openbsd)
  lib9_config = release_openbsd
  libbio_config = release_openbsd
  libsec_config = release_openbsd
  ndate_config = release_openbsd
  node9_config = release_openbsd
  libnode9_config = release_openbsd
endif
ifeq ($(config),release_dragonfly)
  lib9_config = release_dragonfly
  libbio_config = release_dragonfly
  libsec_config = release_dragonfly
  ndate_config = release_dragonfly
  node9_config = release_dragonfly
  libnode9_config = release_dragonfly
endif
ifeq ($(config),release_solaris)
  lib9_config = release_solaris
  libbio_config = release_solaris
  libsec_config = release_solaris
  ndate_config = release_solaris
  node9_config = release_solaris
  libnode9_config = release_solaris
endif
ifeq ($(config),release_windows)
  lib9_config = release_windows
  libbio_config = release_windows
  libsec_config = release_windows
  ndate_config = release_windows
  node9_config = release_windows
  libnode9_config = release_windows
endif
ifeq ($(config),release_android)
  lib9_config = release_android
  libbio_config = release_android
  libsec_config = release_android
  ndate_config = release_android
  node9_config = release_android
  libnode9_config = release_android
endif

PROJECTS := lib9 libbio libsec ndate node9 libnode9

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

lib9:
ifneq (,$(lib9_config))
	@echo "==== Building lib9 ($(lib9_config)) ===="
	@${MAKE} --no-print-directory -C . -f lib9.make config=$(lib9_config)
endif

libbio:
ifneq (,$(libbio_config))
	@echo "==== Building libbio ($(libbio_config)) ===="
	@${MAKE} --no-print-directory -C . -f libbio.make config=$(libbio_config)
endif

libsec:
ifneq (,$(libsec_config))
	@echo "==== Building libsec ($(libsec_config)) ===="
	@${MAKE} --no-print-directory -C . -f libsec.make config=$(libsec_config)
endif

ndate:
ifneq (,$(ndate_config))
	@echo "==== Building ndate ($(ndate_config)) ===="
	@${MAKE} --no-print-directory -C . -f ndate.make config=$(ndate_config)
endif

node9:
ifneq (,$(node9_config))
	@echo "==== Building node9 ($(node9_config)) ===="
	@${MAKE} --no-print-directory -C . -f node9.make config=$(node9_config)
endif

libnode9:
ifneq (,$(libnode9_config))
	@echo "==== Building libnode9 ($(libnode9_config)) ===="
	@${MAKE} --no-print-directory -C . -f libnode9.make config=$(libnode9_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f lib9.make clean
	@${MAKE} --no-print-directory -C . -f libbio.make clean
	@${MAKE} --no-print-directory -C . -f libsec.make clean
	@${MAKE} --no-print-directory -C . -f ndate.make clean
	@${MAKE} --no-print-directory -C . -f node9.make clean
	@${MAKE} --no-print-directory -C . -f libnode9.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_linux"
	@echo "  debug_macosx"
	@echo "  debug_freebsd"
	@echo "  debug_netbsd"
	@echo "  debug_openbsd"
	@echo "  debug_dragonfly"
	@echo "  debug_solaris"
	@echo "  debug_windows"
	@echo "  debug_android"
	@echo "  devel_linux"
	@echo "  devel_macosx"
	@echo "  devel_freebsd"
	@echo "  devel_netbsd"
	@echo "  devel_openbsd"
	@echo "  devel_dragonfly"
	@echo "  devel_solaris"
	@echo "  devel_windows"
	@echo "  devel_android"
	@echo "  release_linux"
	@echo "  release_macosx"
	@echo "  release_freebsd"
	@echo "  release_netbsd"
	@echo "  release_openbsd"
	@echo "  release_dragonfly"
	@echo "  release_solaris"
	@echo "  release_windows"
	@echo "  release_android"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   lib9"
	@echo "   libbio"
	@echo "   libsec"
	@echo "   ndate"
	@echo "   node9"
	@echo "   libnode9"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
