# GNU Make solution makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  lib9_config = debug
  libbio_config = debug
  libsec_config = debug
  ndate_config = debug
  node9_config = debug
  libnode9_config = debug
endif
ifeq ($(config),release)
  lib9_config = release
  libbio_config = release
  libsec_config = release
  ndate_config = release
  node9_config = release
  libnode9_config = release
endif

PROJECTS := lib9 libbio libsec ndate node9 libnode9

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

lib9:
ifneq (,$(lib9_config))
	@echo "==== Building lib9 ($(lib9_config)) ===="
	@${MAKE} --no-print-directory -C . -f lib9.make config=$(lib9_config)
endif

libbio:
ifneq (,$(libbio_config))
	@echo "==== Building libbio ($(libbio_config)) ===="
	@${MAKE} --no-print-directory -C . -f libbio.make config=$(libbio_config)
endif

libsec:
ifneq (,$(libsec_config))
	@echo "==== Building libsec ($(libsec_config)) ===="
	@${MAKE} --no-print-directory -C . -f libsec.make config=$(libsec_config)
endif

ndate:
ifneq (,$(ndate_config))
	@echo "==== Building ndate ($(ndate_config)) ===="
	@${MAKE} --no-print-directory -C . -f ndate.make config=$(ndate_config)
endif

node9:
ifneq (,$(node9_config))
	@echo "==== Building node9 ($(node9_config)) ===="
	@${MAKE} --no-print-directory -C . -f node9.make config=$(node9_config)
endif

libnode9:
ifneq (,$(libnode9_config))
	@echo "==== Building libnode9 ($(libnode9_config)) ===="
	@${MAKE} --no-print-directory -C . -f libnode9.make config=$(libnode9_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f lib9.make clean
	@${MAKE} --no-print-directory -C . -f libbio.make clean
	@${MAKE} --no-print-directory -C . -f libsec.make clean
	@${MAKE} --no-print-directory -C . -f ndate.make clean
	@${MAKE} --no-print-directory -C . -f node9.make clean
	@${MAKE} --no-print-directory -C . -f libnode9.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   lib9"
	@echo "   libbio"
	@echo "   libsec"
	@echo "   ndate"
	@echo "   node9"
	@echo "   libnode9"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
